In [314]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import  warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('instagram_reels_recommendation_features.csv')
df = data.copy() 
df.head()

df.columns

df.info()

df.shape

print(df["topic"].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1913 entries, 0 to 1912
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   description             996 non-null    object
 1   hashtags                1698 non-null   object
 2   url                     1014 non-null   object
 3   account_id              1013 non-null   object
 4   likes                   1013 non-null   object
 5   comments                1003 non-null   object
 6   topic                   1679 non-null   object
 7   video_id                1913 non-null   object
 8   clean_description       964 non-null    object
 9   clean_hashtags          1698 non-null   object
 10  combined_features_text  1913 non-null   object
 11  likes_count             1913 non-null   int64
 12  comments_count          1913 non-null   int64
 13  total_engagement        1913 non-null   int64
 14  video_duration_sec      1913 non-null   int64
 15  days_since_published    1913 non-null   int64
dtypes: int64(5), object(11)
memory usage: 239.3+ KB
topic
Fitness          119
Education        117
Society          114
Trends            95
Comedy            93
Cinema            86
Sports            80
Technology        80
Motivation        78
Relationships     71
Spirituality      70
Travel            65
Music             63
Animals           60
Knowledge         57
Food              54
Fashion           51
Architecture      47
Photography       45
Healthcare        43
Wildlife          41
Crafts            39
Dance             33
Business          31
Gaming            26
Festivals         21
Name: count, dtype: int64

In [315]:
df.describe()

        likes_count  comments_count  total_engagement  video_duration_sec  days_since_published
count  1.913000e+03     1913.000000      1.913000e+03         1913.000000           1913.000000
mean   2.566353e+05     1501.951385      2.611412e+05           33.928385             92.290643
std    7.956266e+05     6413.193917      8.073122e+05           15.603199             52.661062
min    0.000000e+00        0.000000      0.000000e+00            7.000000              1.000000
25%    0.000000e+00        0.000000      0.000000e+00           21.000000             46.000000
50%    1.380000e+02       19.000000      1.536000e+03           34.000000             94.000000
75%    1.270000e+05      773.000000      1.294960e+05           47.000000            139.000000
max    1.100000e+07   150000.000000      1.116500e+07           60.000000            179.000000

In [316]:
df["topic"]

0              Sports
1                 NaN
2       Relationships
3              Comedy
4              Gaming
            ...
1908         Business
1909         Business
1910         Business
1911         Business
1912         Business
Name: topic, Length: 1913, dtype: object

In [317]:
df.isna().sum()

description               917
hashtags                  215
url                       899
account_id                900
likes                     900
comments                  910
topic                     234
video_id                    0
clean_description         949
clean_hashtags            215
combined_features_text      0
likes_count                 0
comments_count              0
total_engagement            0
video_duration_sec          0
days_since_published        0
dtype: int64

In [318]:
df.duplicated().sum()

np.int64(0)

In [319]:
df.head(4)

                          description  ... days_since_published
0                           Day 68     ...                  168
1                                 NaN  ...                   92
2  Tag someone 🤡❤️..........           ...                   97
3                 Yen anthira 🤣🤣       ...                   59

[4 rows x 16 columns]

In [320]:
df = df[['description','hashtags','topic','likes','comments','account_id']]
df.head()

                          description  ...             account_id
0                           Day 68     ...  dancing_chicken.daily
1                                 NaN  ...              vana.cumm
2  Tag someone 🤡❤️..........           ...        quoteswriter___
3                 Yen anthira 🤣🤣       ...      yashwanth_shettyy
4   Do you remember this guy???  go    ...          doc.nostalgia

[5 rows x 6 columns]

In [321]:
df.isna().sum()

description    917
hashtags       215
topic          234
likes          900
comments       910
account_id     900
dtype: int64

In [322]:
df = df.dropna()
df.head()
df.isna().sum()

description    0
hashtags       0
topic          0
likes          0
comments       0
account_id     0
dtype: int64

In [323]:
df.iloc[0]['hashtags']

'#reels #fyp #barcelona #realmadrid'

In [324]:
df['tags'] = df['description'] + df['hashtags']
df.head()

                                         description  ...                                               tags
0                                          Day 68     ...        Day 68   #reels #fyp #barcelona #realmadrid
2                 Tag someone 🤡❤️..........           ...  Tag someone 🤡❤️..........         #reelsindia ...
3                                Yen anthira 🤣🤣       ...  Yen anthira 🤣🤣     #reels #comedy #kannadareel...
4                  Do you remember this guy???  go    ...  Do you remember this guy???  go  #pokemon #pok...
6  I wish I could recreate this… most requested t...  ...  I wish I could recreate this… most requested t...

[5 rows x 7 columns]

In [325]:
df['tags'][2]

'Tag someone 🤡❤️..........         #reelsindia #reelsvideos #instareels #instagramreels #friendshipquotes #friendshipquote #explorepage #explore'

In [326]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import string

In [327]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Acer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [328]:
pip install emoji

Requirement already satisfied: emoji in c:\users\acer\anaconda3\lib\site-packages (2.15.0)
Note: you may need to restart the kernel to use updated packages.

In [329]:
import emoji

In [330]:
# Create tags column
df['tags'] = (
    df['description'].fillna('') + ' ' +
    df['hashtags'].fillna('') + ' ' +
    df['topic'].fillna('')
)

# Convert to lowercase
df['tags'] = df['tags'].str.lower()


# Remove emojis BEFORE tokenization
df['tags'] = df['tags'].apply(lambda x: emoji.replace_emoji(x, replace=''))


# Tokenize
df['tags'] = df['tags'].apply(word_tokenize)

# Remove stopwords
stop_words = set(stopwords.words('english'))

df['tags'] = df['tags'].apply(
    lambda words: [word for word in words if word not in stop_words]
)

# Remove Punctuation
df['tags'] = df['tags'].apply(
    lambda words: [word for word in words if word not in string.punctuation]
)

# Lemmatization
lemmatizer = WordNetLemmatizer() 
df['tags'] = df['tags'].apply(
    lambda words : [lemmatizer.lemmatize(word) for word in words]
)
# Join tokens back into text
df['tags'] = df['tags'].apply(lambda words: " ".join(words)) 

df[['tags']].head()

                                                tags
0         day 68 reel fyp barcelona realmadrid sport
2  tag someone .......... reelsindia reelsvideos ...
3  yen anthira reel comedy kannadareels yashwanth...
4  remember guy go pokemon pokemongo nostalgia re...
6  wish could recreate this… requested too•••••••...

In [331]:
df.head()

                                         description  ...                                               tags
0                                          Day 68     ...         day 68 reel fyp barcelona realmadrid sport
2                 Tag someone 🤡❤️..........           ...  tag someone .......... reelsindia reelsvideos ...
3                                Yen anthira 🤣🤣       ...  yen anthira reel comedy kannadareels yashwanth...
4                  Do you remember this guy???  go    ...  remember guy go pokemon pokemongo nostalgia re...
6  I wish I could recreate this… most requested t...  ...  wish could recreate this… requested too•••••••...

[5 rows x 7 columns]

In [332]:
df['tags'][3]

'yen anthira reel comedy kannadareels yashwanthshetty kannadacomedy bengaluru comedy'

In [333]:
df.duplicated().sum()

np.int64(2)

In [334]:
df = df[df.duplicated()]
df

                                           description  ...                                               tags
152  You have your girl or Queen??Share with her......  ...  girl queen share .... instagram reel reelsinst...
779  AI Era is coming soon 🔜...            beautifu...  ...  ai era coming soon ... beautiful ingreels sins...

[2 rows x 7 columns]

In [335]:
df.drop_duplicates(subset='tags',inplace=True)

In [336]:
df.duplicated().sum()

np.int64(0)

Vectorization

In [337]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

tfidf_matrix = tfidf.fit_transform(df['tags'])
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 88 stored elements and shape (2, 83)>

Cosine Similarity

In [340]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

# -------------------------------
# Reset Index
# -------------------------------
df = df.reset_index(drop=True)

# -------------------------------
# Cosine Similarity Matrix
# -------------------------------
cosine_sim = cosine_similarity(tfidf_matrix)

# -------------------------------
# Recommendation Function
# -------------------------------

def recommend(topic, n=10):

    # Topic exists?
    if topic not in df["topic"].unique():
        return "Reel not found"

    # Get ALL rows belonging to that topic
    topic_indices = df[df["topic"] == topic].index.tolist()

    # Average similarity of all reels in that topic
    avg_similarity = cosine_sim[topic_indices].mean(axis=0)

    # Remove same-topic reels
    avg_similarity[topic_indices] = -1

    # Top recommendations
    recommended_indices = np.argsort(avg_similarity)[::-1][:n]

    return df.loc[
        recommended_indices,
        [
            "description",
            "account_id",
            "topic",
            "likes",
            "comments"
        ]
    ].reset_index(drop=True)


# -------------------------------
# Test
# -------------------------------

recommend("Trends")

                                         description      account_id   topic  likes comments
0  AI Era is coming soon 🔜...            beautifu...  rudra_raaajput  Comedy  32.6K      106
1  You have your girl or Queen??Share with her......    ankush__lift  Trends   564K    4,386

In [339]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))